### ISSUE TITLE
Tesseract vs Cloud Vision

### ISSUE THREAD

**Issue by TheSecureTux** [GrafeasGroup/tor_ocr#15]
Hi team! I'm the guy who coded image-to-text-bot ( https://github.com/jmg87/image-to-text-reddit-bot ) before even knowing that yours existed. Through /r/TranscribersOfReddit they let me know about your project.

What I can see is that, as me, you applied the OCR with the package "Tesseract". I got quite poor results with that one, so I moved to the Google Cloud Vision API (both projects are developed by Google, but the later seems to get much much more accurate results with no image tweaking at all).

I checked and I've been able to use that as they give you 1000 image transcriptions a month for free, far more than what I'm using. Anyway, so, have you considered maybe giving it a try? In my repo this is already implemented, or maybe I can give you a hand on anything.

**Comment by NGTmeaty** [comment]
Hey! We have currently moved away from Tesseract and are using a service called ocr.space. This works much better for our needs, it is run off the Microsoft Cloud API. @perryprog coded our integration and he would be the perfect person to ask questions.

**Comment by perryprog** [comment]
👋 hey there!

As @NGTmeaty said, we were originally using Tesseract (I'm now realizing the README isn't updated yet), but it was way too slow and inaccurate to offer any real help to your transcribers.

I moved the project onto [ocr.space](https://ocr.space), which uses Microsoft's Azure OCR API if I recall correctly. The reason we're using that, and not something else, is mainly due to pricing. 

The Google Cloud Vision API's free pricing plan wouldn't work too well for us, as we're doing between 400 and 700 calls a day.

If you have any questions, I'd be happy to answer them! 😄

**Comment by itsthejoker** [comment]
Yes, OCR.space is based off of Microsoft's Vision Services. Unfortunately, there is no free solution on the market that matches our requirements, which kind of sucks.

Also wow yeah that readme is horribly out of date. We should fix this.

Since this isn't actually an issue, I'm going to close it but feel free to continue to use it for discussion. :wave:
